#!/usr/bin/env bash

# Regenerates docs/trace/S1.md from READ-ONLY checks only (no creates).

source scripts/_common.sh

TRACE_FILE="docs/trace/S1.md"
mkdir -p docs/trace

need gcloud
need bq
need psql
need python3
need docker

: "${PROJECT:?PROJECT is required in .env}"
: "${REGION:?REGION is required in .env}"
: "${INSTANCE:?INSTANCE is required in .env}"
: "${BUCKET:?BUCKET is required in .env}"
: "${DEMO_SOURCE:?DEMO_SOURCE is required in .env}"

OPERATOR="$(gcloud config get-value account 2>/dev/null || echo unknown)"
TIMESTAMP="$(date -u +"%Y-%m-%dT%H:%M:%SZ")"
RAW_DS="${DEMO_SOURCE}_raw"
CORE_DS="${DEMO_SOURCE}_core"
BUCKET_URI="gs://${BUCKET}"

PASS_N=0
FAIL_N=0
declare -A CHECKLIST

section() {
  local id="$1"
  local title="$2"
  printf '\n## %s — %s\n\n' "$id" "$title" >>"$TRACE_FILE"
}

record_cmd() {
  local cmd="$1"
  printf '### Command\n\n```bash\n%s\n```\n\n' "$cmd" >>"$TRACE_FILE"
}

record_output() {
  local out="$1"
  # Mask any DSN-shaped secrets before writing.
  local masked
  masked="$(printf '%s' "$out" | mask)"
  printf '### Output\n\n```\n%s\n```\n\n' "$masked" >>"$TRACE_FILE"
}

record_result() {
  local result="$1"
  printf '### Result: **%s**\n\n' "$result" >>"$TRACE_FILE"
  if [[ "$result" == "PASS" ]]; then
    PASS_N=$((PASS_N + 1))
  else
    FAIL_N=$((FAIL_N + 1))
  fi
}

set_checklist() {
  local key="$1"
  local result="$2"
  CHECKLIST["$key"]="$result"
}

run_readonly() {
  # Captures stdout+stderr without failing the script on non-zero.
  set +e
  # shellcheck disable=SC2086
  OUT="$(eval "$@" 2>&1)"
  RC=$?
  set -e
}

# Overwrite the trace file completely.
{
  printf '# Sprint 1 Trace (S1)\n\n'
  printf '| Field | Value |\n|---|---|\n'
  printf '| project | %s |\n' "$PROJECT"
  printf '| region | %s |\n' "$REGION"
  printf '| timestamp (UTC) | %s |\n' "$TIMESTAMP"
  printf '| operator (gcloud account) | %s |\n' "$OPERATOR"
  printf '\n> Regenerated by `scripts/06_trace.sh` — read-only verifications only.\n'
} >"$TRACE_FILE"

# ---------------------------------------------------------------------------
# S1-T00 — Tools
# ---------------------------------------------------------------------------
section "S1-T00" "Tools on PATH"
CMD='command -v gcloud psql python3 docker'
record_cmd "$CMD"
run_readonly 'command -v gcloud; command -v psql; command -v python3; command -v docker'
record_output "$OUT"
if (( RC == 0 )); then
  record_result "PASS"
else
  record_result "FAIL"
fi

# ---------------------------------------------------------------------------
# S1-T01 — Project and billing
# ---------------------------------------------------------------------------
section "S1-T01" "Project and billing"
CMD="gcloud projects describe ${PROJECT}; gcloud beta billing projects describe ${PROJECT}"
record_cmd "$CMD"
run_readonly "gcloud projects describe '${PROJECT}' --format='yaml(projectNumber,lifecycleState,projectId)'"
PROJ_OUT="$OUT"
PROJ_RC=$RC
run_readonly "gcloud beta billing projects describe '${PROJECT}' --format='yaml(billingEnabled,billingAccountName)'"
BILL_OUT="$OUT"
BILL_RC=$RC
record_output "${PROJ_OUT}"$'\n'"${BILL_OUT}"

PN="$(gcloud projects describe "$PROJECT" --format='value(projectNumber)' 2>/dev/null || true)"
STATE="$(gcloud projects describe "$PROJECT" --format='value(lifecycleState)' 2>/dev/null || true)"
BILL="$(gcloud beta billing projects describe "$PROJECT" --format='value(billingEnabled)' 2>/dev/null || true)"
if [[ "$PN" == "153115538723" && "$STATE" == "ACTIVE" && "$BILL" == "True" ]]; then
  record_result "PASS"
  set_checklist "project+billing" "PASS"
else
  record_result "FAIL"
  set_checklist "project+billing" "FAIL"
fi

# ---------------------------------------------------------------------------
# S1-T02 — Seven APIs
# ---------------------------------------------------------------------------
section "S1-T02" "Required APIs enabled"
SERVICES=(
  sqladmin.googleapis.com
  run.googleapis.com
  bigquery.googleapis.com
  storage.googleapis.com
  artifactregistry.googleapis.com
  secretmanager.googleapis.com
  cloudbuild.googleapis.com
)
CMD="gcloud services list --enabled --filter='config.name:(${SERVICES[*]})'"
record_cmd "$CMD"
API_LINES=""
API_OK=1
for svc in "${SERVICES[@]}"; do
  run_readonly "gcloud services list --enabled --project='${PROJECT}' --filter='config.name=${svc}' --format='value(config.name)'"
  API_LINES+="${svc}=${OUT:-MISSING}"$'\n'
  if [[ "$OUT" != "$svc" ]]; then
    API_OK=0
  fi
done
record_output "$API_LINES"
if (( API_OK == 1 )); then
  record_result "PASS"
  set_checklist "7 APIs" "PASS"
else
  record_result "FAIL"
  set_checklist "7 APIs" "FAIL"
fi

# ---------------------------------------------------------------------------
# S1-T03 — Cloud SQL instance
# ---------------------------------------------------------------------------
section "S1-T03" "Cloud SQL instance"
CMD="gcloud sql instances describe ${INSTANCE}"
record_cmd "$CMD"
run_readonly "gcloud sql instances describe '${INSTANCE}' --project='${PROJECT}' --format='yaml(name,state,settings.tier,settings.backupConfiguration.pointInTimeRecoveryEnabled,settings.backupConfiguration.startTime,connectionName)'"
record_output "$OUT"
SQL_STATE="$(gcloud sql instances describe "$INSTANCE" --project="$PROJECT" --format='value(state)' 2>/dev/null || true)"
SQL_TIER="$(gcloud sql instances describe "$INSTANCE" --project="$PROJECT" --format='value(settings.tier)' 2>/dev/null || true)"
SQL_PITR="$(gcloud sql instances describe "$INSTANCE" --project="$PROJECT" --format='value(settings.backupConfiguration.pointInTimeRecoveryEnabled)' 2>/dev/null || true)"
SQL_START="$(gcloud sql instances describe "$INSTANCE" --project="$PROJECT" --format='value(settings.backupConfiguration.startTime)' 2>/dev/null || true)"
if [[ "$SQL_STATE" == "RUNNABLE" && "$SQL_TIER" == "db-g1-small" && "$SQL_PITR" == "True" && "$SQL_START" == "19:00" ]]; then
  record_result "PASS"
  set_checklist "Cloud SQL instance" "PASS"
else
  record_result "FAIL"
  set_checklist "Cloud SQL instance" "FAIL"
fi

# ---------------------------------------------------------------------------
# S1-T04 — Databases
# ---------------------------------------------------------------------------
section "S1-T04" "Cloud SQL databases (collector, sentinel_mock)"
CMD="gcloud sql databases list --instance=${INSTANCE}"
record_cmd "$CMD"
run_readonly "gcloud sql databases list --instance='${INSTANCE}' --project='${PROJECT}' --format='table(name)'"
record_output "$OUT"
DB_LIST="$(gcloud sql databases list --instance="$INSTANCE" --project="$PROJECT" --format='value(name)' 2>/dev/null || true)"
if printf '%s\n' "$DB_LIST" | grep -Fxq "collector"; then
  set_checklist "collector db" "PASS"
  COLLECTOR_DB=1
else
  set_checklist "collector db" "FAIL"
  COLLECTOR_DB=0
fi
if printf '%s\n' "$DB_LIST" | grep -Fxq "sentinel_mock"; then
  set_checklist "sentinel_mock db" "PASS"
  MOCK_DB=1
else
  set_checklist "sentinel_mock db" "FAIL"
  MOCK_DB=0
fi
if (( COLLECTOR_DB == 1 && MOCK_DB == 1 )); then
  record_result "PASS"
else
  record_result "FAIL"
fi

# ---------------------------------------------------------------------------
# S1-T05 — GCS bucket
# ---------------------------------------------------------------------------
section "S1-T05" "GCS raw bucket"
CMD="gcloud storage buckets describe ${BUCKET_URI}"
record_cmd "$CMD"
run_readonly "gcloud storage buckets describe '${BUCKET_URI}' --project='${PROJECT}' --format='yaml(name,location,uniform_bucket_level_access,public_access_prevention,lifecycle_config)'"
record_output "$OUT"
BLOC="$(gcloud storage buckets describe "$BUCKET_URI" --project="$PROJECT" --format='value(location)' 2>/dev/null | tr '[:lower:]' '[:upper:]' || true)"
PAP="$(gcloud storage buckets describe "$BUCKET_URI" --project="$PROJECT" --format='value(public_access_prevention)' 2>/dev/null | tr '[:upper:]' '[:lower:]' || true)"
if [[ -z "$PAP" ]]; then
  PAP="$(gcloud storage buckets describe "$BUCKET_URI" --project="$PROJECT" --format='value(iamConfiguration.publicAccessPrevention)' 2>/dev/null | tr '[:upper:]' '[:lower:]' || true)"
fi
if [[ "$BLOC" == "ASIA-SOUTH1" && "$PAP" == "enforced" ]]; then
  record_result "PASS"
  set_checklist "GCS bucket" "PASS"
else
  record_result "FAIL"
  set_checklist "GCS bucket" "FAIL"
fi

# ---------------------------------------------------------------------------
# S1-T06 — BigQuery datasets
# ---------------------------------------------------------------------------
section "S1-T06" "BigQuery datasets (${RAW_DS}, ${CORE_DS})"
CMD="bq show ${PROJECT}:${RAW_DS}; bq show ${PROJECT}:${CORE_DS}"
record_cmd "$CMD"
run_readonly "bq show --format=prettyjson '${PROJECT}:${RAW_DS}'"
RAW_OUT="$OUT"
run_readonly "bq show --format=prettyjson '${PROJECT}:${CORE_DS}'"
CORE_OUT="$OUT"
record_output "${RAW_OUT}"$'\n---\n'"${CORE_OUT}"
RAW_LOC="$(printf '%s' "$RAW_OUT" | python3 -c 'import json,sys; print(json.load(sys.stdin).get("location","").lower())' 2>/dev/null || true)"
CORE_LOC="$(printf '%s' "$CORE_OUT" | python3 -c 'import json,sys; print(json.load(sys.stdin).get("location","").lower())' 2>/dev/null || true)"
if [[ "$RAW_LOC" == "asia-south1" ]]; then
  set_checklist "sentinel_raw" "PASS"
  RAW_OK=1
else
  set_checklist "sentinel_raw" "FAIL"
  RAW_OK=0
fi
if [[ "$CORE_LOC" == "asia-south1" ]]; then
  set_checklist "sentinel_core" "PASS"
  CORE_OK=1
else
  set_checklist "sentinel_core" "FAIL"
  CORE_OK=0
fi
if (( RAW_OK == 1 && CORE_OK == 1 )); then
  record_result "PASS"
else
  record_result "FAIL"
fi

# ---------------------------------------------------------------------------
# S1-T07 — Service accounts and secrets
# ---------------------------------------------------------------------------
section "S1-T07" "Service accounts and Secret Manager"
SA_WORKER_EMAIL="${SA_WORKER:-collector-sentinel@${PROJECT}.iam.gserviceaccount.com}"
SA_API_EMAIL="${SA_API:-collector-api@${PROJECT}.iam.gserviceaccount.com}"
SA_MOCK_EMAIL="${SA_MOCK:-mock-sentinel@${PROJECT}.iam.gserviceaccount.com}"
CMD="gcloud iam service-accounts describe …; gcloud secrets versions access latest --secret=…"
record_cmd "$CMD"

SA_OUT=""
SA_OK=1
for email in "$SA_WORKER_EMAIL" "$SA_API_EMAIL" "$SA_MOCK_EMAIL"; do
  run_readonly "gcloud iam service-accounts describe '${email}' --project='${PROJECT}' --format='value(email)'"
  SA_OUT+="${email} => ${OUT:-MISSING}"$'\n'
  if [[ "$OUT" != "$email" ]]; then
    SA_OK=0
  fi
done

if [[ "$SA_WORKER_EMAIL" == *"collector-sentinel@"* ]] && gcloud iam service-accounts describe "$SA_WORKER_EMAIL" --project="$PROJECT" >/dev/null 2>&1; then
  set_checklist "collector-sentinel" "PASS"
else
  set_checklist "collector-sentinel" "FAIL"
  SA_OK=0
fi
if gcloud iam service-accounts describe "$SA_API_EMAIL" --project="$PROJECT" >/dev/null 2>&1; then
  set_checklist "collector-api" "PASS"
else
  set_checklist "collector-api" "FAIL"
  SA_OK=0
fi
if gcloud iam service-accounts describe "$SA_MOCK_EMAIL" --project="$PROJECT" >/dev/null 2>&1; then
  set_checklist "mock-sentinel" "PASS"
else
  set_checklist "mock-sentinel" "FAIL"
  SA_OK=0
fi

SECRET_OUT=""
SECRET_OK=1
for secret_id in collector-dsn sentinel-mock-dsn; do
  run_readonly "gcloud secrets versions access latest --secret='${secret_id}' --project='${PROJECT}'"
  if (( RC == 0 )); then
    SECRET_OUT+="${secret_id} => $(printf '%s' "$OUT" | mask)"$'\n'
    set_checklist "$secret_id" "PASS"
  else
    SECRET_OUT+="${secret_id} => MISSING/UNREADABLE"$'\n'
    set_checklist "$secret_id" "FAIL"
    SECRET_OK=0
  fi
done
record_output "${SA_OUT}"$'\n'"${SECRET_OUT}"
if (( SA_OK == 1 && SECRET_OK == 1 )); then
  record_result "PASS"
else
  record_result "FAIL"
fi

# ---------------------------------------------------------------------------
# S1-T08 — Artifact Registry
# ---------------------------------------------------------------------------
section "S1-T08" "Artifact Registry repository lisn"
CMD="gcloud artifacts repositories describe lisn --location=${REGION}"
record_cmd "$CMD"
run_readonly "gcloud artifacts repositories describe lisn --location='${REGION}' --project='${PROJECT}' --format='yaml(name,format)'"
record_output "$OUT"
REPO_FMT="$(gcloud artifacts repositories describe lisn --location="$REGION" --project="$PROJECT" --format='value(format)' 2>/dev/null | tr '[:lower:]' '[:upper:]' || true)"
REPO_NAME="$(gcloud artifacts repositories describe lisn --location="$REGION" --project="$PROJECT" --format='value(name)' 2>/dev/null || true)"
EXPECTED_REPO="projects/${PROJECT}/locations/${REGION}/repositories/lisn"
if [[ "$REPO_FMT" == "DOCKER" && "$REPO_NAME" == "$EXPECTED_REPO" ]]; then
  record_result "PASS"
  set_checklist "Artifact Registry" "PASS"
else
  record_result "FAIL"
  set_checklist "Artifact Registry" "FAIL"
fi

# ---------------------------------------------------------------------------
# S1-T09 — Worker pools + budget alert (read-only signals)
# ---------------------------------------------------------------------------
section "S1-T09" "Worker-pools availability and billing budget alert"
CMD="gcloud beta run worker-pools list --region=${REGION}; gcloud billing budgets list"
record_cmd "$CMD"

WP_OUT=""
if gcloud beta run worker-pools --help >/dev/null 2>&1 && \
  gcloud beta run worker-pools list --region="$REGION" --project="$PROJECT" >/dev/null 2>&1; then
  WP_OUT="worker-pools: AVAILABLE"
  set_checklist "worker-pools availability" "PASS"
  WP_OK=1
else
  WP_OUT="worker-pools: NOT AVAILABLE — fallback is Cloud Run jobs with --tasks=3"
  set_checklist "worker-pools availability" "FAIL"
  WP_OK=0
fi

BILLING_ACCOUNT="$(
  gcloud beta billing projects describe "$PROJECT" \
    --format='value(billingAccountName)' 2>/dev/null || true
)"
BUDGET_OUT="billingAccount=${BILLING_ACCOUNT:-unknown}"
BUDGET_OK=0
if [[ -n "$BILLING_ACCOUNT" ]]; then
  BA_ID="${BILLING_ACCOUNT##*/}"
  run_readonly "gcloud billing budgets list --billing-account='${BA_ID}' --format='table(displayName,name)'"
  BUDGET_OUT+=$'\n'"$OUT"
  if [[ -n "$OUT" ]] && ! printf '%s' "$OUT" | grep -qi 'Listed 0 items\|did not match'; then
    # Any non-empty budget listing counts as present for the pilot checklist.
    if printf '%s' "$OUT" | grep -Eq 'projects/|billingBudgets/|[A-Za-z0-9_-]+'; then
      BUDGET_OK=1
    fi
  fi
fi
if (( BUDGET_OK == 1 )); then
  set_checklist "budget alert" "PASS"
else
  set_checklist "budget alert" "FAIL"
  BUDGET_OUT+=$'\n(no billing budget detected — set a budget alert for Cloud SQL spend)'
fi

record_output "${WP_OUT}"$'\n'"${BUDGET_OUT}"
if (( WP_OK == 1 && BUDGET_OK == 1 )); then
  record_result "PASS"
else
  # Informational for worker-pools; still mark section FAIL if either checklist row fails.
  record_result "FAIL"
fi

# ---------------------------------------------------------------------------
# Exit checklist (16 rows)
# ---------------------------------------------------------------------------
{
  printf '\n## Exit checklist\n\n'
  printf '| Check | Result |\n|---|---|\n'
  for key in \
    "project+billing" \
    "7 APIs" \
    "Cloud SQL instance" \
    "collector db" \
    "sentinel_mock db" \
    "GCS bucket" \
    "sentinel_raw" \
    "sentinel_core" \
    "collector-sentinel" \
    "collector-api" \
    "mock-sentinel" \
    "collector-dsn" \
    "sentinel-mock-dsn" \
    "Artifact Registry" \
    "budget alert" \
    "worker-pools availability"
  do
    printf '| %s | %s |\n' "$key" "${CHECKLIST[$key]:-FAIL}"
  done
  printf '\n## Summary\n\n'
  printf '%s\n' '- sections PASS-ish count (S1-T00..T09 recorded results): see section Result lines'
  printf '%s\n' '- checklist rows above are the Sprint 1 exit gate inventory'
  printf '%s\n' '- passwords/DSNs in this file are masked via `mask()`'
} >>"$TRACE_FILE"

ok "Regenerated ${TRACE_FILE}"
ok "Trace sections with FAIL count this run: ${FAIL_N} (PASS markers: ${PASS_N})"
echo "Trace file: ${TRACE_FILE}"
